input {
  tcp {
    port => 4560
    codec => json
  }
}

filter {
  if ![span][id] and [mdc][spanId] {
    mutate { rename => { "[mdc][spanId]" => "[span][id]" } }
  }
  if ![trace][id] and [mdc][traceId] {
    mutate { rename => { "[mdc][traceId]" => "[trace][id]" } }
  }
}

output {
  stdout {}
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => true
    data_stream_auto_routing => false
    data_stream_type => "logs"
    data_stream_dataset => "producer"
    data_stream_namespace => "default"
  }
}
