quarkus.log.console.json=false

# Write structured JSON logs to a file that Promtail will tail
quarkus.log.file.enable=true
quarkus.log.file.json=true
quarkus.log.file.path=/deployments/logs/application.log
quarkus.log.file.json.exception-output-type=formatted
quarkus.log.file.json.log-format=ECS
